#===============================================================================
# Copyright contributors to the oneDAL project
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
#===============================================================================

name: Nightly-build

on:
  schedule:
    - cron: '0 21 * * *'
  workflow_dispatch:

permissions:
  contents: read

jobs:
  build_lnx:
    name: oneDAL Linux nightly build
    runs-on: ubuntu-22.04
    timeout-minutes: 120

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        run: .ci/env/apt.sh dpcpp
      - name: Install MKL
        run: .ci/env/apt.sh mkl
      - name: System Info
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/describe_system.sh
      - name: Make daal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target daal
      - name: Make onedal
        run: |
          source /opt/intel/oneapi/compiler/latest/env/vars.sh
          .ci/scripts/build.sh --compiler icx  --optimizations avx2 --target onedal
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_lnx
          path: ./__release_lnx

  build_win:
    name: oneDAL Windows nightly build
    runs-on: windows-2022
    timeout-minutes: 120

    steps:
      - name: Checkout oneDAL
        uses: actions/checkout@v4
        with:
          repository: oneapi-src/oneDAL
      - name: Install DPC++
        shell: cmd
        run: |
          .ci/scripts/install_windows.bat https://registrationcenter-download.intel.com/akdlm/IRC_NAS/d91caaa0-7306-46ea-a519-79a0423e1903/w_BaseKit_p_2024.2.1.101_offline.exe intel.oneapi.win.cpp-dpcpp-common:intel.oneapi.win.mkl.devel
      - name: System Info
        shell: cmd
        run: |
          set PATH=C:\msys64\usr\bin;%PATH%
          pip install cpufeature
          call C:\temp\oneapi\setvars.bat
          bash .ci/scripts/describe_system.sh
      - name: Make daal
        shell: cmd
        run: |
          call .\.ci\scripts\build.bat daal vc avx2
      - name: Make onedal
        shell: cmd
        run: |
          call .\.ci\scripts\build.bat onedal_c vc avx2
      - name: Make oneapi_dpc
        shell: cmd
        run: |
          call .\dpcpp\compiler\latest\env\vars.bat
          call .\dpcpp\compiler\latest\bin\sycl-ls.exe
          call .\.ci\scripts\build.bat onedal_dpc vc avx2
      - name: Archive build
        uses: actions/upload-artifact@v4
        with:
          name: __release_win
          path: .\__release_win_vc
      - name: Compress DPC++
        shell: cmd
        run: |
          tar -cvzf icx.zip .\dpcpp
      - name: Archive DPC++
        uses: actions/upload-artifact@v4
        with:
          name: icx_compiler
          path: .\icx.zip
      - name: Archive Intel OpenCL CPU runtime
        uses: actions/upload-artifact@v4
        with:
          name: opencl_rt_installer
          path: .\opencl_rt.msi
